---
- name: Cloner nudger-vm avec PAT GitHub
  hosts: master1
  become: true
  vars:
    repo_url: "https://github.com/logo-solutions/nudger-vm.git"
    git_pat: "{{ lookup('env','GITHUB_PAT') }}"   # ou via ansible-vault

  tasks:
    - name: Vérifier que git est installé
      apt:
        name: git
        state: present
      become: true

    - name: Cloner ou mettre à jour nudger-vm
      git:
        repo: "https://{{ git_pat }}@github.com/logo-solutions/nudger-vm.git"
        dest: "/root/nudger-vm"
        version: main
        force: yes
