alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias vu='vagrant up'
alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias k='kubectl'
alias kd='kubectl describe'
alias kcc='kubectl config current-context'
alias kg='kubectl get'
alias kga='kubectl get all --all-namespaces'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias ksgp='kubectl get pods -n kube-system'
alias kss='kubectl get services -n kube-system'
alias kuc='kubectl config use-context'
alias gitq='git add -A && git commit -m "clean" && git push'
alias cash='$HOME/nudger/scripts/cat.sh'
alias cdn='cd $HOME/logo-solutions/nudger-vm'
alias cdo='cd $HOME/nudger-gitops'
alias cdi='cd $HOME/nudger-infra'
alias cs='/home/ops-loic-1/nudger-gitops/scripts/git/commit-safe.sh fix: autocommit'
alias ke='kubectl get events -A --watch --sort-by=.metadata.creationTimestamp'
alias aliass='. //home/ops-loic-1/nudger/config-vm/.bash_aliases'
alias aliasv='vim /home/ops-loic-1/nudger/config-vm/.bash_aliases'
alias tag='$HOME/logo-solutions/nudger-vm/scripts/git/tag.sh'
