alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias vu='vagrant up'
alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias k='kubectl'
alias kd='kubectl describe'
alias kcc='kubectl config current-context'
alias kg='kubectl get'
alias kga='kubectl get all --all-namespaces'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias ksgp='kubectl get pods -n kube-system'
alias kss='kubectl get services -n kube-system'
alias kuc='kubectl config use-context'
alias gitq='git add -A && git commit -m "clean" && git push'
alias cash='$LOGO_DIR/nudger-vm/scripts/cat.sh'
alias cdn='cd $LOGO_DIR/nudger-vm'
alias cdi='cd $LOGO_DIR/nudger-infra'
alias ke='kubectl get events -A --watch --sort-by=.metadata.creationTimestamp'
alias aliass='. $LOGO_DIR/nudger-vm/scripts/profile-bashrc/.bash_aliases'
alias aliasv='vim $LOGO_DIR/nudger-vm/scripts/profile-bashrc/.bash_aliases'
alias tag='$LOGO_DIR/nudger-vm/scripts/git/tag.sh'
alias sshm='ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i ~/.ssh/hetzner-bastion root@91.98.16.184'
alias sshb='ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/hetzner-bastion root@157.180.42.146'
alias gcp='$LOGO_DIR/nudger-vm/scripts/git/gcp.sh'
